# Generated by Django 4.2.4 on 2024-07-16 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cartoon", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactme",
            old_name="fullname",
            new_name="fname",
        ),
        migrations.RenameField(
            model_name="contactme",
            old_name="message",
            new_name="msg",
        ),
    ]
