# Generated by Django 4.2.4 on 2024-07-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartoon", "0002_rename_fullname_contactme_fname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactme",
            name="phn",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
